---
- name: enable netconf-yang on csr1
  hosts: all
  connection: network_cli
  tasks:
    - name: configuration commands
      ios_config:
        lines:
        - netconf-yang
    - name: show commands
      ios_command:
        commands:
          - show netconf-yang status

